services:
  nginx:
    image: nginx:alpine
    container_name: sample-bg-nginx
    ports:
      - "8081:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blue
      - green

  blue:
    image: traefik/whoami:latest
    container_name: sample-bg-blue
    profiles: ["blue"]
    ports:
      - "8082:80"

  green:
    image: traefik/whoami:latest
    container_name: sample-bg-green
    profiles: ["green"]
    ports:
      - "8083:80"
