---
- name: 20) AWS - Create VPC/Subnet/SG (API from control node)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vpc_name: ansible-lab-vpc
    vpc_cidr: 10.10.0.0/16
    subnet_name: ansible-lab-public-subnet
    subnet_cidr: 10.10.1.0/24
    sg_name: ansible-lab-sg

    aws_tags:
    Name: ansible-lab
    Environment: dev
    ManagedBy: ansible

  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        tags: "{{ aws_tags }}"
      register: vpc

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ aws_region }}"
        tags: "{{ aws_tags | combine({'Name': subnet_name}) }}"
      register: subnet

    - name: Create security group (allow 22,80)
      amazon.aws.ec2_security_group:
        name: "{{ sg_name }}"
        description: Ansible lab SG
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        tags: "{{ aws_tags }}"
      register: sg

    - name: Save outputs (vpc/subnet/sg) to local file
      ansible.builtin.copy:
        dest: ./aws_outputs.yml
        content: |
          aws_region: {{ aws_region }}
          vpc_id: {{ vpc.vpc.id }}
          subnet_id: {{ subnet.subnet.id }}
          sg_id: {{ sg.group_id }}
